//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_TASK_DOC
    {
        public int ID { get; set; }
        public Nullable<int> PROJECT_TASK_ID { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string DOC_URL { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<int> DELETE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual PROJECT_TASK PROJECT_TASK { get; set; }
        public virtual TASK_RELATED_DOC TASK_RELATED_DOC { get; set; }
    }
}
